### ISSUE TITLE
Test for git actions

### ISSUE THREAD

**Issue by darkdarcool** [kokonut27/kokonut27#5]
Just a test

**Comment by kokonut27** [comment]
Lol ok

**Comment by darkdarcool** [comment]
it didn't work

**Comment by iop3** [comment]
indeed.

**Comment by iop3** [comment]
Did you generate a token @JBYT27?

**Comment by kokonut27** [comment]
Ah, thats why it prob didnt work lmao. Ill try that asap - thanks!

**Comment by iop3** [comment]
NP

**Comment by kokonut27** [comment]
Oh, it works, you just have to be new to my github profile entirely
> view actions and workflows
